example:
  irrelevant_subdomains:
  metadata_keep:
  checker_functions:
  other_info_funcs:

spektrum_medizin:
  irrelevant_subdomains:
    - /lexikon/
    - /pdf/
    - /abo/
    - /inhaltsverzeichnis/
    - /quiz/
    - /podcast/
    - /shop/
    - /bundle/
    - /alias/
    - /video/
  metadata_keep:
    - og:title
    - og:type
    - og:description
    - og:url
    - article:publisher
    - article:author
    - og:image
    - article:opinion
    - article:location
    - article:content_tier
  checker_functions:
  other_info_funcs:
    - get_h1

stern_gesundheit:
  irrelevant_subdomains:
    - template=gallery
    - /podcast--
    - /themen/
    - --video--
  metadata_keep:
    - description
    - date
    - last-modified
    - buildDate
    - og:locale
    - og:type
    - og:title
    - og:description
    - article:opinion
    - og:url
  checker_functions:
    - stern_is_free

apothekenumschau:
  irrelevant_subdomains:
    - .pdfhttps:/
    - /unsere-marken/
    - /produkte/
    - /rss/
    - /impressum/
    - /kontakt/
    - /ueber-uns/
    - /img/
    - /unterhaltung/memo
    - /quiz-
    - /unterhaltung/(?!interview/)[\w/-]+
    - /rezepte/
    - /buchstabe-[a-z]-
    - \.ico
    - /wirkstofflisten/
    - /beipackzettel/
    - /english/
  metadata_keep:
    - author
    - article:section
    - article:tag
    - publisher
    - article:author
    - keywords
    - description
    - date
    - og:type
    - og:site_name
    - og:title
    - og:description
    - og:updated_time
    - article:modified_time
    - article:published_time
  checker_functions:
  other_info_funcs:
    - get_h1


focus_gesundheit:
  irrelevant_subdomains:
    - /video/
    - /tests/
    - ^(?!.*\.html$).*$
  metadata_keep:
    - description
    - og:description
    - date
    - author
    - fol_ct
    - fol:articleid
    - article:content_tier
  checker_functions:
  other_info_funcs:
    - get_h1


paradisi_forum:
  irrelevant_subdomains:
    - /themen/formel
  metadata_keep:
    - description
  checker_functions:
    - paradisi_forum_is_health


tonline_gesundheit:
  irrelevant_subdomains:
    - /video/
    - /tests/
    - ^(?!.*\.html$).*$
  metadata_keep:
    - language
    - company
    - description
    - article:opinion
    - article:published_time
  checker_functions:
  other_info_funcs:
    - get_h1


gesundheitsinformation:
  irrelevant_subdomains:
  metadata_keep:
  checker_functions:
  other_info_funcs:
    - get_h1
